plugins:
  - jekyll-sitemap

exclude:      ['Gemfile', 'Gemfile.lock', 'README.md', 'config.ru', 'vendor']

sass:
  sass_dir:   css/_scss
  style:      compressed

assets:
  compress:
    css:      default
    js:       default
    img:      default

  autowrite:  true

  assets:
    - 'main.css'
    - '*.js'
    - '*.png'
    - '*.jpg'
    - '*.svg'

  sources:
    - css
    - js
    - images
    - _posts/images

# ------------------------

# Build settings
markdown:     kramdown

# Texts
main:
  title:      'Fisioeffect'
  titleTag:   'Fisioeffect'
  keywords:   'fisioterapia fisioterapeuta domicilio madrid'

terms:
  title:      'Aviso Legal'

cookies:
  title:      'Política de cookies'
  titleTag:   'Política de cookies'
